<h1>Welcome to <span class="zf-green">zFrame</span></h1>
<p>Congratulations! You have successfully installed the zFrame Skeleton Application. You are currently running zFrame version 1.0 . This skeleton can serve as a simple starting point for you to begin building your application on zFrame.</p>

<?php $this->block->include_block('Demo/Index/Index', 'Demo/View/Block/Block.phtml'); ?>

<?php $this->view->beginSlot('test');?>
<h3>test</h3>
<h3>test</h3>
<h3>test</h3>
<?php $this->view->endSlot('test');?>